name: Deno

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_deno:
    name: Ensure Deno types are in sync with the code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: package.json

      - name: Install Dependencies
        run: yarn

      - name: Run Check Script
        run: node ./scripts/actions/report-deno-not-ran.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
